{{- if .Values.services.qbittorrent.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: qbittorrent
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: qbittorrent
spec:
  revisionHistoryLimit: 3
  replicas: {{ .Values.services.qbittorrent.replicaCount }}
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app.kubernetes.io/name: qbittorrent
  template:
    metadata:
      labels:
        app.kubernetes.io/name: qbittorrent
    spec:
      containers:
        - name: qbittorrent
          image: "{{ .Values.services.qbittorrent.image.repository }}:{{ .Values.services.qbittorrent.image.tag }}"
          imagePullPolicy: {{ .Values.services.qbittorrent.image.pullPolicy }}
          env:
            - name: PUID
              value: "1000"
            - name: PGID
              value: "1000"
            - name: TZ
              value: "{{ .Values.common.tz }}"
            - name: WEBUI_PORT
              value: "{{ .Values.services.qbittorrent.ports.http }}"
          ports:
            - name: http
              containerPort: {{ .Values.services.qbittorrent.ports.http }}
              protocol: TCP
            - name: p2p
              containerPort: {{ .Values.services.qbittorrent.ports.p2p }}
              protocol: TCP
            - name: p2pudp
              containerPort: {{ .Values.services.qbittorrent.ports.p2pudp }}
              protocol: UDP
          volumeMounts:
            - name: qbittorrent-config
              mountPath: /config
              subPath: qbittorrent
            - name: data
              mountPath: /data
      volumes:
        - name: qbittorrent-config
          {{- if .Values.storage.nfs.enabled }}
          persistentVolumeClaim:
            claimName: media-config-pvc
          {{- else }}
          hostPath:
            path: "{{ .Values.services.qbittorrent.config }}"
            type: Directory
          {{- end }}
        - name: data
          {{- if .Values.storage.nfs.enabled }}
          persistentVolumeClaim:
            claimName: media-data-pvc
          {{- else }}
          hostPath:
            path: "{{ .Values.services.qbittorrent.data }}"
            type: Directory
          {{- end }}
{{- end }}
