{{- if .Values.services.qbittorrent.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: qbittorrent
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: qbittorrent
spec:
  revisionHistoryLimit: 3
  replicas: {{ .Values.services.qbittorrent.replicaCount }}
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app.kubernetes.io/name: qbittorrent
  template:
    metadata:
      labels:
        app.kubernetes.io/name: qbittorrent
    spec:
    
      containers:
        - name: gluetun
          image: ghcr.io/qdm12/gluetun # Optionally you can use the "qmcgaw/gluetun" image as well as specify what version of Gluetun you desire
          imagePullPolicy: Always
          securityContext:
            capabilities:
              add: ["NET_ADMIN"]
           # Adapt the following environment variables to suit your needs and VPN provider
          env:
            - name: TZ
              value: "{{ .Values.common.tz }}"
            - name: VPN_SERVICE_PROVIDER
              value: "mullvad"
            - name: VPN_TYPE
              value: "wireguard"
            - name: WIREGUARD_PRIVATE_KEY
              valueFrom:
                secretKeyRef:
                  name: gluetun-secrets
                  key: wireguard_private_key
            - name: WIREGUARD_ADDRESSES
              valueFrom:
                secretKeyRef:
                  name: gluetun-secrets
                  key: wireguard_addresses
          lifecycle:
            postStart:
              exec:
                command: ["/bin/sh", "-c", "(ip rule del table 51820; ip -6 rule del table 51820) || true"]
    
        - name: qbittorrent
          image: "{{ .Values.services.qbittorrent.image.repository }}:{{ .Values.services.qbittorrent.image.tag }}"
          imagePullPolicy: {{ .Values.services.qbittorrent.image.pullPolicy }}
          env:
            - name: PUID
              value: "1000"
            - name: PGID
              value: "1000"
            - name: TZ
              value: "{{ .Values.common.tz }}"
            - name: WEBUI_PORT
              value: "{{ .Values.services.qbittorrent.ports.http }}"
          ports:
            - name: http
              containerPort: {{ .Values.services.qbittorrent.ports.http }}
              protocol: TCP
            - name: p2p
              containerPort: {{ .Values.services.qbittorrent.ports.p2p }}
              protocol: TCP
            - name: p2pudp
              containerPort: {{ .Values.services.qbittorrent.ports.p2pudp }}
              protocol: UDP
          volumeMounts:
            - name: qbittorrent-config
              mountPath: /config
            - name: data
              mountPath: /data
      volumes:
        - name: qbittorrent-config
          hostPath:
            path: "{{ .Values.services.qbittorrent.config }}"
            type: Directory
        - name: data
          hostPath:
            path: "{{ .Values.services.qbittorrent.data }}"
            type: Directory
{{- end }}
