apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: qbittorrent
  annotations:
    gethomepage.dev/href: "https://qbittorrent.{{ .Values.services.nginx.domain }}"
    gethomepage.dev/enabled: "true"
    gethomepage.dev/description: "qbittorrent ."
    gethomepage.dev/group: "Media"
    gethomepage.dev/name: "qbittorrent"
    gethomepage.dev/pod-selector: ""
spec:
  parentRefs:
    - name: traefik-gateway
      namespace:  traefik
  hostnames:
    - "qbittorrent.{{ .Values.services.nginx.domain }}"
  rules:
     - matches:
        - path:
            type: PathPrefix
            value: /
       backendRefs:
        - name: qbittorrent
          namespace: {{ .Release.Namespace }}
          port: {{ .Values.services.qbittorrent.ports.http }}