{{- if .Values.services.changedetectionio.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: changedetectionio
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: changedetectionio
spec:
  type: ClusterIP
  ports:
    - name: http
      port: {{ .Values.services.changedetectionio.ports.http }}
      targetPort: http
      protocol: TCP
  selector:
    app.kubernetes.io/name: changedetectionio
{{- end }}