apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: overseerr
  annotations:
    gethomepage.dev/href: "https://overseerr.{{ .Values.services.nginx.domain }}"
    gethomepage.dev/enabled: "true"
    gethomepage.dev/description: "Overseerr is a request management and media discovery tool for Plex."
    gethomepage.dev/group: "Media"
    gethomepage.dev/name: "overseerr"
    gethomepage.dev/pod-selector: ""
spec:
  parentRefs:
    - name: traefik-gateway
      namespace:  traefik
  hostnames:
    - "overseerr.{{ .Values.services.nginx.domain }}"
  rules:
     - matches:
        - path:
            type: PathPrefix
            value: /
       backendRefs:
        - name: overseerr
          namespace: {{ .Release.Namespace }}
          port: {{ .Values.services.overseerr.ports.http }}
