{{- if .Values.services.plex.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: plex
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: plex
spec:
  revisionHistoryLimit: 3
  replicas: {{ .Values.services.plex.replicaCount }}
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app.kubernetes.io/name: plex
  template:
    metadata:
      labels:
        app.kubernetes.io/name: plex
    spec:
      initContainers:
      containers:
        - name: plex
          image: "{{ .Values.services.plex.image.repository }}:{{ .Values.services.plex.image.tag }}"
          imagePullPolicy: {{ .Values.services.plex.image.pullPolicy }}
          env:
            - name: PUID
              value: "1000"
            - name: PGID
              value: "1000"
            - name: TZ
              value: "{{ .Values.common.tz }}"
            - name: PLEX_CLAIM
              value: "{{ .Values.services.plex.plexClaim }}"
          ports:
            - name: http
              containerPort: {{ .Values.services.plex.ports.http }}
              protocol: TCP
          volumeMounts:
            - name: plex-config
              mountPath: /config
              {{- if not .Values.services.plex.localStorage.enabled }}
              subPath: plex
              {{- end }}
            - name: library
              mountPath: /library
      volumes:
        - name: plex-config
          {{- if .Values.services.plex.localStorage.enabled }}
          persistentVolumeClaim:
            claimName: plex-config-local-pvc
          {{- else if .Values.storage.nfs.enabled }}
          persistentVolumeClaim:
            claimName: media-config-pvc
          {{- else }}
          hostPath:
            path: "{{ .Values.services.plex.config }}"
            type: Directory
          {{- end }}
        - name: library
          {{- if .Values.storage.nfs.enabled }}
          persistentVolumeClaim:
            claimName: media-library-pvc
          {{- else }}
          hostPath:
            path: "{{ .Values.services.plex.library }}"
            type: Directory
          {{- end }}
{{- end }}
