apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: plex
  annotations:
    gethomepage.dev/href: "https://plex.{{ .Values.services.nginx.domain }}"
    gethomepage.dev/enabled: "true"
    gethomepage.dev/description: "Plex is a personal media server."
    gethomepage.dev/group: "Media"
    gethomepage.dev/icon: "fas fa-video"
    gethomepage.dev/name: "Plex"
    gethomepage.dev/pod-selector: ""
spec:
  parentRefs:
    - name: traefik-gateway
      namespace:  traefik
  hostnames:
    - "plex.{{ .Values.services.nginx.domain }}"
  rules:
     - matches:
        - path:
            type: PathPrefix
            value: /
       backendRefs:
        - name: plex
          namespace: {{ .Release.Namespace }}
          port: {{ .Values.services.plex.ports.http }}
