{{- if .Values.services.plex.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: plex
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: plex
spec:
  type: ClusterIP
  ports:
    - name: http
      port: {{ .Values.services.plex.ports.http }}
      targetPort: http
      protocol: TCP
  selector:
    app.kubernetes.io/name: plex
{{- end }}
