{{- if .Values.services.prowlarr.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: prowlarr
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: prowlarr
spec:
  revisionHistoryLimit: 3
  replicas: {{ .Values.services.prowlarr.replicaCount }}
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app.kubernetes.io/name: prowlarr
  template:
    metadata:
      labels:
        app.kubernetes.io/name: prowlarr
    spec:
      initContainers:
        - name: install-custom-indexers
          image: alpine/git:latest
          command:
            - sh
            - -c
            - |
              DEST="/config/Definitions/Custom"
              mkdir -p "$DEST"
              TMP=$(mktemp -d)
              git clone --depth 1 https://github.com/dreulavelle/Prowlarr-Indexers.git "$TMP"
              cp -v "$TMP"/Custom/*.yml "$DEST/"
              rm -rf "$TMP"
              echo "Custom indexers installed:"
              ls -la "$DEST/"
          volumeMounts:
            - name: prowlarr-config
              mountPath: /config
              subPath: prowlarr
      containers:
        - name: prowlarr
          image: "{{ .Values.services.prowlarr.image.repository }}:{{ .Values.services.prowlarr.image.tag }}"
          imagePullPolicy: {{ .Values.services.prowlarr.image.pullPolicy }}
          env:
            - name: PUID
              value: "1000"
            - name: PGID
              value: "1000"
            - name: TZ
              value: "{{ .Values.common.tz }}"
          ports:
            - name: http
              containerPort: {{ .Values.services.prowlarr.ports.http }}
              protocol: TCP
          volumeMounts:
            - name: prowlarr-config
              mountPath: /config
              subPath: prowlarr

      volumes:
        - name: prowlarr-config
          {{- if .Values.storage.nfs.enabled }}
          persistentVolumeClaim:
            claimName: media-config-pvc
          {{- else }}
          hostPath:
            path: "{{ .Values.services.prowlarr.config }}"
            type: Directory
          {{- end }}
{{- end }}