{{- if .Values.services.tautulli.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tautulli
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: tautulli
spec:
  revisionHistoryLimit: 3
  replicas: {{ .Values.services.tautulli.replicaCount }}
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app.kubernetes.io/name: tautulli
  template:
    metadata:
      labels:
        app.kubernetes.io/name: tautulli
    spec:
      containers:
        - name: tautulli
          image: "{{ .Values.services.tautulli.image.repository }}:{{ .Values.services.tautulli.image.tag }}"
          imagePullPolicy: {{ .Values.services.tautulli.image.pullPolicy }}
          env:
            - name: PUID
              value: "1000"
            - name: PGID
              value: "1000"
            - name: TZ
              value: "{{ .Values.common.tz }}"
          ports:
            - name: http
              containerPort: {{ .Values.services.tautulli.ports.http }}
              protocol: TCP
          volumeMounts:
            - name: tautulli-config
              mountPath: /config
              subPath: tautulli
      volumes:
        - name: tautulli-config
          {{- if .Values.storage.nfs.enabled }}
          persistentVolumeClaim:
            claimName: media-config-pvc
          {{- else }}
          hostPath:
            path: "{{ .Values.services.tautulli.config }}"
            type: Directory
          {{- end }}
{{- end }}
