apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: sonarr
  annotations:
    gethomepage.dev/href: "https://sonarr.{{ .Values.services.nginx.domain }}"
    gethomepage.dev/enabled: "true"
    gethomepage.dev/description: "Sonarr is a personal media server."
    gethomepage.dev/group: "Media"
    gethomepage.dev/icon: "fas fa-video"
    gethomepage.dev/name: "sonarr"
    gethomepage.dev/pod-selector: ""
spec:
  parentRefs:
    - name: traefik-gateway
      namespace:  traefik
  hostnames:
    - "sonarr.{{ .Values.services.nginx.domain }}"
  rules:
     - matches:
        - path:
            type: PathPrefix
            value: /
       backendRefs:
        - name: sonarr
          namespace: {{ .Release.Namespace }}
          port: {{ .Values.services.sonarr.ports.http }}