{{- if .Values.services.radarr.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: radarr
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: radarr
spec:
  revisionHistoryLimit: 3
  replicas: {{ .Values.services.radarr.replicaCount }}
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app.kubernetes.io/name: radarr
  template:
    metadata:
      labels:
        app.kubernetes.io/name: radarr
    spec:
      {{- if and .Values.services.radarr.localConfig .Values.services.radarr.localConfig.enabled }}
      nodeSelector:
        kubernetes.io/hostname: {{ .Values.services.radarr.localConfig.node }}
      {{- end }}
      containers:
        - name: radarr
          image: "{{ .Values.services.radarr.image.repository }}:{{ .Values.services.radarr.image.tag }}"
          imagePullPolicy: {{ .Values.services.radarr.image.pullPolicy }}
          env:
            - name: PUID
              value: "1000"
            - name: PGID
              value: "1000"
            - name: TZ
              value: "{{ .Values.common.tz }}"
          ports:
            - name: http
              containerPort: {{ .Values.services.radarr.ports.http }}
              protocol: TCP
          volumeMounts:
            - name: radarr-config
              mountPath: /config
              {{- if not (and .Values.services.radarr.localConfig .Values.services.radarr.localConfig.enabled) }}
              subPath: radarr
              {{- end }}
            - name: data
              mountPath: /data

      volumes:
        - name: radarr-config
          {{- if and .Values.services.radarr.localConfig .Values.services.radarr.localConfig.enabled }}
          hostPath:
            path: {{ .Values.services.radarr.localConfig.hostPath }}
            type: DirectoryOrCreate
          {{- else if .Values.storage.nfs.enabled }}
          persistentVolumeClaim:
            claimName: media-config-pvc
          {{- else }}
          hostPath:
            path: "{{ .Values.services.radarr.config }}"
            type: Directory
          {{- end }}
        - name: data
          {{- if .Values.storage.nfs.enabled }}
          persistentVolumeClaim:
            claimName: media-data-pvc
          {{- else }}
          hostPath:
            path: "{{ .Values.services.radarr.data }}"
            type: Directory
          {{- end }}
{{- end }}
