{{- if .Values.services.sabnzbd.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sabnzbd
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: sabnzbd
spec:
  revisionHistoryLimit: 3
  replicas: {{ .Values.services.sabnzbd.replicaCount }}
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app.kubernetes.io/name: sabnzbd
  template:
    metadata:
      labels:
        app.kubernetes.io/name: sabnzbd
    spec:
      containers:
        - name: sabnzbd
          image: "{{ .Values.services.sabnzbd.image.repository }}:{{ .Values.services.sabnzbd.image.tag }}"
          imagePullPolicy: {{ .Values.services.sabnzbd.image.pullPolicy }}
          env:
            - name: PUID
              value: "1000"
            - name: PGID
              value: "1000"
            - name: TZ
              value: "{{ .Values.common.tz }}"
          ports:
            - name: http
              containerPort: {{ .Values.services.sabnzbd.ports.http }}
              protocol: TCP
          volumeMounts:
            - name: sabnzbd-config
              mountPath: /config
              subPath: sabnzbd
            - name: data
              mountPath: /data
      volumes:
        - name: sabnzbd-config
          {{- if .Values.storage.nfs.enabled }}
          persistentVolumeClaim:
            claimName: media-config-pvc
          {{- else }}
          hostPath:
            path: "{{ .Values.services.sabnzbd.config }}"
            type: Directory
          {{- end }}
        - name: data
          {{- if .Values.storage.nfs.enabled }}
          persistentVolumeClaim:
            claimName: media-data-pvc
          {{- else }}
          hostPath:
            path: "{{ .Values.services.sabnzbd.data }}"
            type: Directory
          {{- end }}
{{- end }}
