{{- if .Values.services.debridClient.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: debrid-client
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: debrid-client
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.services.debridClient.ports.http }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: debrid-client
{{- end }}
